# Generated by Django 4.2.13 on 2026-01-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('entity_type', models.CharField(choices=[('concept', 'Concept'), ('person', 'Person'), ('place', 'Place'), ('organization', 'Organization'), ('project', 'Project'), ('topic', 'Topic'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('frequency_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'ordering': ['-frequency_score', '-created_at'],
                'unique_together': {('user', 'name', 'entity_type')},
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('entity_count', models.IntegerField(default=0)),
                ('relationship_count', models.IntegerField(default=0)),
                ('last_indexed', models.DateTimeField(auto_now=True)),
                ('health_score', models.FloatField(default=1.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Graph',
                'verbose_name_plural': 'Knowledge Graphs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('mentions', 'Mentions'), ('related_to', 'Related To'), ('depends_on', 'Depends On'), ('part_of', 'Part Of'), ('similar_to', 'Similar To'), ('created_by', 'Created By'), ('assigned_to', 'Assigned To'), ('references', 'References'), ('custom', 'Custom')], max_length=50)),
                ('strength', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='knowledge_graph.entity')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='knowledge_graph.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
                'ordering': ['-strength', '-created_at'],
                'unique_together': {('source_entity', 'target_entity', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='EntityItemLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mention_count', models.IntegerField(default=1)),
                ('context', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_links', to='knowledge_graph.entity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='api.item')),
            ],
            options={
                'verbose_name': 'Entity Item Link',
                'verbose_name_plural': 'Entity Item Links',
                'unique_together': {('entity', 'item')},
            },
        ),
    ]
