# Generated by Django 4.2.13 on 2026-01-22 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
        ('knowledge_graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('project', 'Project'), ('topic', 'Topic'), ('timeline', 'Timeline'), ('theme', 'Theme'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('item_count', models.IntegerField(default=0)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('algorithm', models.CharField(choices=[('kmeans', 'K-Means'), ('hdbscan', 'HDBSCAN'), ('hierarchical', 'Hierarchical')], default='kmeans', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Smart Collection',
                'verbose_name_plural': 'Smart Collections',
                'ordering': ['-confidence_score', '-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClusterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_strength', models.FloatField(default=1.0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='knowledge_graph.smartcollection')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='api.item')),
            ],
            options={
                'verbose_name': 'Cluster Item',
                'verbose_name_plural': 'Cluster Items',
                'unique_together': {('collection', 'item')},
            },
        ),
    ]
